name: com.example.flutter_cubit_app
description: A simple Flutter application using the Cubit pattern for state management. The application has two screens: a login screen with email and password fields, and a home screen with a logout button.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.0.0
  mocktail: ^0.1.0

flutter:
  uses-material-design: true